apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - |
        touch /tmp/healthy;     #Here created file healthy under tmp dir
        sleep 30;
        rm -f /tmp/healthy;     #And after 30 sec delete it
        sleep 600
    livenessProbe:              #Then container keeps running
      exec:
        command:
          - cat
          - /tmp/healthy        #Every 5 seconds command cat /tmp/healthy will run, & if file exists → success &if not failure
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
