apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
spec:
  containers:
  - name: stress
    image: polinux/stress
    resources:
      limits:
        memory: "100Mi"             #limit 100Mi which is very small
    command: ["stress"]             #And Stress tries to use = 200M, So the Result: Memory exceeds limit → KILLED
    args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
