apiVersion: v1
kind: Pod
metadata:
  name: too-big-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100"       # 100 CPUs (very high)
        memory: "128Gi"  # 128 GB RAM (very high)
