[web]
web-server ansible_host=3.108.194.146

[app]
app-server ansible_host=65.0.102.141

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/sona/trainwithshubham/90DaysOfDevOps/2026/day-73/terraform-practice/my-key.pem
                                                                                  

