services:
  app:
    build: .      #Go to current folder (.) and find a Dockerfile It finds your Dockerfile Starts executing it
    container_name: node_app
    volumes:
      - ./app:/app        # live reload (important) it means whatever chnages we do in the index.html file that will get reflect in the webpage
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
