[web]
web-server ansible_host=13.127.63.252

[app]
web-server

[db]
web-server

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/sona/trainwithshubham/90DaysOfDevOps/2026/day-69/terraform-practice/my-key.pem
                             
