[web]
web-server ansible_host=3.110.186.167

[app]
app-server ansible_host=65.1.86.116

[db]
db-server ansible_host=13.201.97.150

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/sona/trainwithshubham/90DaysOfDevOps/2026/day-68/terraform-practice/my-key.pem
#ansible_ssh_private_key_file=../my-key.pem      #this is relative path

[application:children]
web
app

[all_servers:children]
application
db
