[web]
web-server ansible_host=43.204.28.108 ansible_user=ubuntu

[db]
db-server ansible_host=13.232.60.253 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=../terraform-practice/my-key.pem

#[all]
#web-server ansible_host=13.233.20.248 

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/sona/trainwithshubham/90DaysOfDevOps/2026/day-70/terraform-practice/my-key.pem
