apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels: 
    app: busybox
    environment: dev
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c", "echo hello from busybox && sleep 3600"]

