[web]
web-server ansible_host=3.110.204.168 

[db]
db-server ansible_host=65.0.107.60

[app]
web-server ansible_host=3.110.204.168

#[all]
#web-server ansible_host=13.233.20.248 

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/sona/trainwithshubham/90DaysOfDevOps/2026/day-71/terraform-practice/my-key.pem
