apiVersion: v1
kind: Pod
metadata:
  name: busybox-env
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "APP_ENV=$APP_ENV"
        echo "APP_DEBUG=$APP_DEBUG"
        echo "APP_PORT=$APP_PORT"
        sleep 3600
    envFrom:
    - configMapRef:
        name: app-config
