apiVersion: v1
kind: Pod
metadata:
  name: configmap-live-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "Message: $(cat /etc/config/message)";
            sleep 5;
          done
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true

  volumes:
    - name: config-volume
      configMap:
        name: live-config
