apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod                               #Pod name in the cluster
spec:
  containers:
    - name: app
      image: nginx
      env:                                            #Inject Secret as Environment Variable, This measn Create an environment variable inside the container
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER

      volumeMounts:                                  #Mount a volume inside container at: /etc/db-credentials
        - name: secret-volume
          mountPath: /etc/db-credentials
          readOnly: true                            #readOnly: true → Good security practice (you shouldn’t modify secrets)

  volumes:                                          #This connects the volume to the Secret, Take Secret: db-credentials & Convert each key into a file
    - name: secret-volume
      secret:                                        
        secretName: db-credentials
